In [1]:
import torch
import numpy as np

## Initialize Random Dimensions
i, j, k, l = 2, 3, 4, 5
d, e, f = 2, 3, 4

In [2]:
# ======== PART 1 ========== #
a = torch.rand(i,j,k)
b = torch.rand(i)
torch.einsum('ijk,i->jk', [a,b])

tensor([[0.7106, 0.4751, 0.1074, 0.5050],
        [0.1874, 0.2060, 0.7560, 0.3683],
        [0.6379, 0.1714, 0.3815, 0.3631]])

In [3]:
# ======== PART 2 ========== #
a = torch.rand(i,j,k,l)
torch.einsum('ijkl->ik', [a])

tensor([[8.6774, 6.9416, 7.9800, 9.1784],
        [7.6658, 6.9323, 8.4024, 6.5398]])

In [4]:
# ======== PART 3 ========== #
a = torch.rand(i,j,k,l)
torch.einsum('ijkl->ki', [a])

tensor([[7.2821, 9.2879],
        [6.0479, 6.9824],
        [7.4921, 8.1196],
        [6.1522, 6.0205]])

In [5]:
# ======== PART 4 ========== #
a = torch.rand(i,j,k)
torch.einsum('ijk,ijk->i', [a,a])

tensor([3.4680, 3.6339])

In [6]:
# ======== PART 5 ========== #
a = torch.rand(d,e)
g = torch.rand(f,e)
b = torch.rand(f,l)
torch.einsum('de,fe,fl->dl', [a,g,b])

tensor([[2.4761, 2.0254, 2.0391, 2.0957, 0.9469],
        [1.3587, 1.0664, 1.1010, 1.1357, 0.5326]])